ARG UBI_IMAGE

FROM ${UBI_IMAGE} as ubi

FROM scratch

LABEL maintainer "LoZ Open Source Ecosystem (https://www.ibm.com/developerworks/community/groups/community/lozopensource)"

ADD licenses/ /licenses
ADD LICENSE /licenses/

# Include libraries from UBI for dynamic linking.
COPY --from=ubi /lib64 /lib64
COPY --from=ubi /lib /lib

ADD bin/s390x/ /opt/cni/bin/

ENV PATH=$PATH:/opt/cni/bin
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/install"]
